name: sawaari
description:  Sawaari is an online low cost alternative to other ride booking serivice providing the cheapest possible fare to its customers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mapbox_maps_flutter: ^2.8.0
  location: ^5.0.0
  http: ^1.1.0
  font_awesome_flutter: ^10.5.0
  flutter_spinkit: ^5.2.0
  flutter_rating_bar: ^4.0.1
  introduction_screen: ^3.1.12
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  dio: ^5.4.3
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.14.0
  card_swiper: ^2.0.4
  fl_chart: ^0.63.0
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.0.0
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_animations: ^1.1.1
  sliding_up_panel: ^2.0.0+1
  provider: ^6.1.2
  group_button: ^5.3.2
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10
  webview_flutter: ^4.4.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/icon_taxi/
    - assets/style/
    - assets/image/svg/
    - assets/image/marker/
